
const env = {
    BASE_SERVER_URL: process.env.REACT_APP_BASE_SERVER_URL,
    MEDIA_UPLOAD_URL: process.env.REACT_APP_MEDIA_UPLOAD_URL,
    FRONTEND_URL: process.env.REACT_APP_FRONTEND_URL,
    GOOGLE_API_KEY: process.env.REACT_APP_GOOGLE_API_KEY,
    GOOGLE_MAP_LAT: process.env.REACT_APP_GOOGLE_MAP_LAT,
    GOOGLE_MAP_LNG: process.env.REACT_APP_GOOGLE_MAP_LNG,
    GOOGLE_ANALYTICS_ID: process.env.REACT_APP_GOOGLE_ANALYTICS_ID,
    GOOGLE_TAG_MANAGER_ID: process.env.REACT_APP_GOOGLE_TAG_MANAGER_ID,
    GOOGLE_SIGN_IN_CLIENT_ID: process.env.REACT_APP_GOOGLE_SIGN_IN_CLIENT_ID,
    DEMO_LESSON_ID: process.env.REACT_APP_DEMO_LESSON_ID,
    DEMO_LESSON_COURSE_ID: process.env.REACT_APP_DEMO_LESSON_COURSE_ID,
    MEDIA_MAX_UPLOADING_COUNT: process.env.REACT_APP_MEDIA_MAX_UPLOADING_COUNT,
    INTERCOM_APP_ID: process.env.REACT_APP_INTERCOM_APP_ID,
    HOT_JAR_TRACKING_ID: process.env.REACT_APP_HOT_JAR_TRACKING_ID,
    FACEBOOK_PIXEL_ID: process.env.REACT_APP_FACEBOOK_PIXEL_ID,
    SENTRY_DSN: process.env.REACT_APP_SENTRY_DSN,
    STRIPE_PUBLIC_KEY: process.env.REACT_APP_STRIPE_PUBLIC_KEY,
    CDN_DOMAIN: process.env.REACT_APP_CDN_DOMAIN,
};

export {env};